### ISSUE TITLE
Output to AsciiDoc

### ISSUE THREAD

**Issue by lordofthejars** [sdaschner/jaxrs-analyzer#10]
Currently the output of analysis can be a Swagger output or plain text, it will be awesome to have support for AsciiDoc as well.
If you agree I can spend some time in future.

**Comment by sdaschner** [comment]
Yes! This was already on my list. In fact I started the first version with AsciiDoc... Will do that.

**Comment by lordofthejars** [comment]
Ok so I give you this feature to your hands :). If you need any help in AsciiDoc format feel free to ask. Also if you need any help in AsciiDoc/Asciidoctor feel free to ask me or @mojavelinux

**Comment by mojavelinux** [comment]
:+1:

**Comment by sdaschner** [comment]
See 59e6ad2 for a first version. Feel free to re-open this issue. Thanks!

**Comment by mojavelinux** [comment]
\o/

**Comment by lordofthejars** [comment]
Great!!!!

**Comment by sdaschner** [comment]
Included in the latest v0.4 version.
