### ISSUE TITLE
Javadoc analysis fails on Windows

### ISSUE THREAD

**Issue by vboerchers** [sdaschner/jaxrs-analyzer#100]
JavaDoc analysis doesn't work on Windows due to a bug in the handling of paths: On Windows path components regularly contain colons like in `C:\some\path`. This clashes with the unconditional use of ":" as a path separator in the JavaDoc invocation since the resulting argument for `-classpath` is something like this: `C:\some\path:C:\some\other\path`
 
All places where a fixed path separator of ":" is assumed have to be replaced by `File.pathSeparator` for Windows compatibilty.

**Comment by sdaschner** [comment]
Oh yes, you're right -- I always tend forget those Windows guys as Unix fanboy :-)

thanks!
