### ISSUE TITLE
Otuput to LibreOffice

### ISSUE THREAD

**Issue by lordofthejars** [sdaschner/jaxrs-analyzer#11]
Currently the output of analysis can be a Swagger output or plain text, it will be awesome to have support for LibreOffice as well.
If you agree I can spend some time in future.

**Comment by sdaschner** [comment]
So with LibreOffice you mean the .odt format? If there is a need for this, sure.
Feel free to fork & PR.
Thanks for collaborating :-)

**Comment by lordofthejars** [comment]
Ok I will see if we need this requirement in our company so I can spend some time in developing it.

**Comment by sdaschner** [comment]
Added in #37
