### ISSUE TITLE
Support For Generics

### ISSUE THREAD

**Issue by oluwasayo** [sdaschner/jaxrs-analyzer#12]
It would be great if generic types in API responses are supported. A lot of API responses are usually made up of generic types.

Example:

    public Response getUsers() {
       List<User> users = someList;
       return Response.ok(users).build();
    }

**Comment by sdaschner** [comment]
Generics are indeed supported and the example above works in the tests. Maybe the Analyzer has no access to the `User` type later on for the backend type analysis... Do you separate your project in several Maven modules or several jars?
