### ISSUE TITLE
Support for Javadoc Comments

### ISSUE THREAD

**Issue by oluwasayo** [sdaschner/jaxrs-analyzer#13]
Generated API has no line of text describing what each operation does. A good case for javadoc! However due to the fact that this analyzer gathers data from bytecode, it does not have the Javadoc available. A possibility might be for the analyzer to gather some data from the source, invoke a build process and gather the remaining information from bytecode. Another option albeit less attractive would be to have a special annotation carry the comment into bytecode.

**Comment by Koxx3** [comment]
any news on this ? thanks !

**Comment by sdaschner** [comment]
Yes, JavaDoc is actually supported in the current version. Thanks for reminding me to close it.
