### ISSUE TITLE
How to use Swagger-Annotations

### ISSUE THREAD

**Issue by jmanteigueiro** [sdaschner/jaxrs-analyzer#132]
Is it possible to use swagger annotations instead of JavaDocs? 

If so, can you provide an example ? Thanks!

**Comment by jmanteigueiro** [comment]
I found out the problem is the version.

In the latest version, 0.15, the JavaDocs are not inserted in the swagger.json

Using the previous version, 0.14, they are.

**Comment by rmpestano** [comment]
Hi @jmanteigueiro, this plugin doesn't use swagger annotations, it reads JaxRS, Javadoc and uses bytecode analysis to create swagger.json.

**Comment by jmanteigueiro** [comment]
Oh I see... Okay then

I'm now to rest services and all that

Sent from ProtonMail mobile

-------- Original Message --------
