### ISSUE TITLE
Return type is not picked up correctly?

### ISSUE THREAD

**Issue by tbee** [sdaschner/jaxrs-analyzer#134]
My source looks like this:
    @GET
    @Path("/{code}")
    @Produces(MediaType.APPLICATION_JSON + ";charset=UTF-8")
    public ServerVirtual select(@PathParam("code") String code, @HeaderParam("Authorization") String authorizationHeader) {

Note the ServerVirtual class being returned. But the generated swagger (and other files) say that upon a OK it returns a status entity (which is returned on an error or by POST/PUT).
                    "200":{
                        "description":"OK",
                        "headers":{
                        },
                        "schema":{
                            "$ref":"#/definitions/Status"
                        }
                    },

**Comment by sdaschner** [comment]
Could you provide some contents of the `select` method -- especially in regards to the error cases?
