### ISSUE TITLE
Support For Multiple Classpath Entries

### ISSUE THREAD

**Issue by oluwasayo** [sdaschner/jaxrs-analyzer#15]
Many web projects contain dependencies which themselves contain JAX-RS endpoints. Would be great if this analyzer can (in addition to reading sources from multiple paths) unpack archives and scan for classes to analyze.

**Comment by sdaschner** [comment]
Yes! Actually many users seem to have issues with that.

**Comment by sdaschner** [comment]
Since version 0.5 the CLI tool can now accept several class paths and several "analysis paths" as well. All these paths can either be directories or jar-files!

For examples and a full list of options, please see https://github.com/sdaschner/jaxrs-analyzer/blob/master/README.adoc

**Comment by oluwasayo** [comment]
Great!
