### ISSUE TITLE
Failed tests:   test(com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzerTest): expected:<[rest]> but was:<[]>

### ISSUE THREAD

**Issue by jnorthrup** [sdaschner/jaxrs-analyzer#156]
fails in maven, passes in intellij.

failure:
https://gist.github.com/jnorthrup/5619a9e76889744fd0254772fba81f36

pass: 
![image](https://user-images.githubusercontent.com/73514/38306120-aaaafacc-3839-11e8-91a6-b28bbf196067.png)

**Comment by coding-guy** [comment]
Have a look at issue #110

**Comment by jnorthrup** [comment]
dupe
