### ISSUE TITLE
Wrong result for JAX-RS Response with Generic Collection of enum

### ISSUE THREAD

**Issue by rodakr** [sdaschner/jaxrs-analyzer#164]
Hi

Following Case:

// Enum Class
public `enum` Car {

    Ferrari , Ford, Fiat

}

......................................

@Path("/service")
@RequestScoped
public class CarService   {

 @GET
    @Path("/cars/{id:[0-9][0-9]*}")
    @Produces(MediaType.APPLICATION_JSON)
    public Response getCars(@PathParam("id") long id) {
        `List<Car> mycars =  new ArrayList<Car>(){};`
        return  Response.ok(mycars).build();
    }

}

.............................................
Wrong Result :
..............................................

"responses": {
                    "200": {
                        "description": "OK",
                        "headers": {
                        },
                        "schema": {
                            **"type": "array",
                            "enum": [
                                "Ferrari",
                                "Fiat",
                                "Ford"
                            ]**
                        }
                    }
                }

...................................
Expected Result:
.....................................

"responses": {
                    "200": {
                        "description": "OK",
                        "headers": {
                        },
                        "schema": {
                            "type": "array",
                            **"items": {
                                  "type", "string",
                                  "enum": [
                                        "Ferrari",
                                        "Fiat",
                                         "Ford"
                                     ]
                             }**
                        }
                    }
                }

**Comment by rodakr** [comment]
Generic List<Class> is created correctly.
But if Generic List<enum>  holds "enum" , result is wrong.
If Rest Services Returns just "enum" Type, not a List,  result is correct.

**Comment by rodakr** [comment]
Using `javax.ws.rs.core.GenericEntity<List<enum>>` for JAX-RS Service Response  also produce wrong Result, just empty reference... in swagger yaml/json

**Comment by rodakr** [comment]
jars-analyzer version 0.16, running with `-b swagger `

**Comment by sdaschner** [comment]
Ok, that's interesting... Yes, I think your assumption with `EnumTypeRepresentation` goes into the right direction. I don't know if I can find the time to look into it within the next days, but please feel free to verify it using some tests in the mean time :) Have you seen the https://github.com/sdaschner/jaxrs-analyzer-st project? That helps in verifying local builds.

**Comment by rodakr** [comment]
` @Override `
` public void visit(final TypeRepresentation.EnumTypeRepresentation representation) { `
`    builder.add("type", "string");`
`    if (!representation.getEnumValues().isEmpty()) {`
`        final JsonArrayBuilder array =` `representation.getEnumValues().stream().sorted().collect(Json::createArrayBuilder, JsonArrayBuilder::add, JsonArrayBuilder::add);`
`        if (inCollection) {`
`            builder.add("items", Json.createObjectBuilder().add("enum", array).build());`
`        } else {`
`            builder.add("enum", array);`
`        }`

    }
}

**Comment by rodakr** [comment]
basically last if else fix it from code above

**Comment by rodakr** [comment]
Would be nice if you could release new version :-)

**Comment by rodakr** [comment]
sorry... below correct if else :-)

**Comment by rodakr** [comment]
if (inCollection) {
                        builder.add("items", Json.createObjectBuilder().add("type", "string").add("enum", array).build());
                    } else {
                        builder.add("enum", array);
                    }

**Comment by rodakr** [comment]
https://github.com/sdaschner/jaxrs-analyzer/pull/165

Successfully tested with quite complex swagger contract :-)

**Comment by rodakr** [comment]
Hallo  Sebastian

Hier noch pull request https://github.com/sdaschner/jaxrs-analyzer/pull/165 <https://github.com/sdaschner/jaxrs-analyzer/pull/165> mit dem erfolgreich getesteten fix :-)

Gruss Radek
