### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by hindsholm** [sdaschner/jaxrs-analyzer#166]
The [current release](http://mvnrepository.com/artifact/com.sebastian-daschner/jaxrs-analyzer) in the Maven repository is quite old, it is v. 0.16 from September 2017.
Would a new release be possible?

**Comment by sdaschner** [comment]
Yes that should definitely be updated. I'd like to include a few more things for which I hardly find priority atm. Are there specific features or updates you're missing or just "in general" (totally valid as well)?

**Comment by rmpestano** [comment]
Hi guys, javadoc analysis is failing on some cases for us using the trunk version. Works fine in 0.16.

I'll open a detailed issue with a sample reproducer ASAP.

**Comment by hindsholm** [comment]
I am mostly interested in some of the bug fixes that I made earlier (#148 and #150) because our build fails without them.

**Comment by hindsholm** [comment]
I am mostly interested in some of the bug fixes that I made earlier (#148 and #150) because our build fails without them.

**Comment by rmannibucau** [comment]
up, this is blocker java11 migration due to tools.jar usage in 0.16

**Comment by rmpestano** [comment]
> Hi guys, javadoc analysis is failing on some cases for us using the trunk version. Works fine in 0.16.
I'll open a detailed issue with a sample reproducer ASAP.

Just sent two PRs (#179 and #181) which fixes the issues I was talking about. 

Hope they can get into v0.17.

**Comment by sdaschner** [comment]
Yup, released :-)

**Comment by sdaschner** [comment]
Thanks for all your contributions and sorry (once again) for the delays!
