### ISSUE TITLE
Make Analyzer usable without whole JEE 7 API (Exception on init because of JSON-P loading)

### ISSUE THREAD

**Issue by jeff9finger** [sdaschner/jaxrs-analyzer#25]
Just tried again with the 0.7-SNAPSHOT. 

If this error occurs b/c of something in our API, it would be great to have an idea of what/where etc.

Here is the error. Let me know if you need anything else.

[ERROR] Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT:analyze-jaxrs (default) on project tract-api: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT:analyze-jaxrs failed: An API incompatibility was encountered while executing com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT:analyze-jaxrs: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/jeff/.m2/repository/com/sebastian-daschner/jaxrs-analyzer-maven-plugin/0.7-SNAPSHOT/jaxrs-analyzer-maven-plugin-0.7-SNAPSHOT.jar
[ERROR] urls[1] = file:/Users/jeff/.m2/repository/javax/json/javax.json-api/1.0/javax.json-api-1.0.jar
[ERROR] urls[2] = file:/Users/jeff/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar
[ERROR] urls[3] = file:/Users/jeff/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.7-SNAPSHOT/jaxrs-analyzer-0.7-SNAPSHOT.jar
[ERROR] urls[4] = file:/Users/jeff/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[5] = file:/Users/jeff/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[6] = file:/Users/jeff/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
[ERROR] urls[7] = file:/Users/jeff/.m2/repository/org/apache/maven/maven-builder-support/3.3.3/maven-builder-support-3.3.3.jar
[ERROR] urls[8] = file:/Users/jeff/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[9] = file:/Users/jeff/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[10] = file:/Users/jeff/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.5/sisu-guice-3.2.5-no_aop.jar
[ERROR] urls[11] = file:/Users/jeff/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[12] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[13] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[14] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[15] = file:/Users/jeff/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[16] = file:/Users/jeff/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: javassist.NotFoundException: javax.json.Json
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT:analyze-jaxrs (default) on project tract-api: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT:analyze-jaxrs failed: An API incompatibility was encountered while executing com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT:analyze-jaxrs: java.lang.ExceptionInInitializerError: null
-----------------------------------------------------
realm =    plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/jeff/.m2/repository/com/sebastian-daschner/jaxrs-analyzer-maven-plugin/0.7-SNAPSHOT/jaxrs-analyzer-maven-plugin-0.7-SNAPSHOT.jar
urls[1] = file:/Users/jeff/.m2/repository/javax/json/javax.json-api/1.0/javax.json-api-1.0.jar
urls[2] = file:/Users/jeff/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar
urls[3] = file:/Users/jeff/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.7-SNAPSHOT/jaxrs-analyzer-0.7-SNAPSHOT.jar
urls[4] = file:/Users/jeff/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
urls[5] = file:/Users/jeff/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
urls[6] = file:/Users/jeff/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
urls[7] = file:/Users/jeff/.m2/repository/org/apache/maven/maven-builder-support/3.3.3/maven-builder-support-3.3.3.jar
urls[8] = file:/Users/jeff/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
urls[9] = file:/Users/jeff/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
urls[10] = file:/Users/jeff/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.5/sisu-guice-3.2.5-no_aop.jar
urls[11] = file:/Users/jeff/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
urls[12] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
urls[13] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
urls[14] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[15] = file:/Users/jeff/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[16] = file:/Users/jeff/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT:analyze-jaxrs failed: An API incompatibility was encountered while executing com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT:analyze-jaxrs: java.lang.ExceptionInInitializerError: null
-----------------------------------------------------
realm =    plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/jeff/.m2/repository/com/sebastian-daschner/jaxrs-analyzer-maven-plugin/0.7-SNAPSHOT/jaxrs-analyzer-maven-plugin-0.7-SNAPSHOT.jar
urls[1] = file:/Users/jeff/.m2/repository/javax/json/javax.json-api/1.0/javax.json-api-1.0.jar
urls[2] = file:/Users/jeff/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar
urls[3] = file:/Users/jeff/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.7-SNAPSHOT/jaxrs-analyzer-0.7-SNAPSHOT.jar
urls[4] = file:/Users/jeff/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
urls[5] = file:/Users/jeff/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
urls[6] = file:/Users/jeff/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
urls[7] = file:/Users/jeff/.m2/repository/org/apache/maven/maven-builder-support/3.3.3/maven-builder-support-3.3.3.jar
urls[8] = file:/Users/jeff/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
urls[9] = file:/Users/jeff/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
urls[10] = file:/Users/jeff/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.5/sisu-guice-3.2.5-no_aop.jar
urls[11] = file:/Users/jeff/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
urls[12] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
urls[13] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
urls[14] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[15] = file:/Users/jeff/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[16] = file:/Users/jeff/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:183)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT:analyze-jaxrs: java.lang.ExceptionInInitializerError: null
-----------------------------------------------------
realm =    plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7-SNAPSHOT
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/jeff/.m2/repository/com/sebastian-daschner/jaxrs-analyzer-maven-plugin/0.7-SNAPSHOT/jaxrs-analyzer-maven-plugin-0.7-SNAPSHOT.jar
urls[1] = file:/Users/jeff/.m2/repository/javax/json/javax.json-api/1.0/javax.json-api-1.0.jar
urls[2] = file:/Users/jeff/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar
urls[3] = file:/Users/jeff/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.7-SNAPSHOT/jaxrs-analyzer-0.7-SNAPSHOT.jar
urls[4] = file:/Users/jeff/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
urls[5] = file:/Users/jeff/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
urls[6] = file:/Users/jeff/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
urls[7] = file:/Users/jeff/.m2/repository/org/apache/maven/maven-builder-support/3.3.3/maven-builder-support-3.3.3.jar
urls[8] = file:/Users/jeff/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
urls[9] = file:/Users/jeff/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
urls[10] = file:/Users/jeff/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.5/sisu-guice-3.2.5-no_aop.jar
urls[11] = file:/Users/jeff/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
urls[12] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
urls[13] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
urls[14] = file:/Users/jeff/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[15] = file:/Users/jeff/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[16] = file:/Users/jeff/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:181)
	... 21 more
Caused by: java.lang.ExceptionInInitializerError
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.KnownResponseResultMethod.<clinit>(KnownResponseResultMethod.java:52)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodPool.<init>(MethodPool.java:58)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodPool.<clinit>(MethodPool.java:44)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.<init>(MethodSimulator.java:43)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.ResourceMethodContentAnalyzer.<init>(ResourceMethodContentAnalyzer.java:47)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodAnalyzer.<init>(MethodAnalyzer.java:57)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.project.classes.ClassAnalyzer.analyzeInternal(ClassAnalyzer.java:117)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.project.classes.ClassAnalyzer.analyze(ClassAnalyzer.java:65)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer$$Lambda$20/1078814676.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:84)
	at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:69)
	at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo.execute(JAXRSAnalyzerMojo.java:118)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.lang.RuntimeException: javassist.NotFoundException: javax.json.Json
	at com.sebastian_daschner.jaxrs_analyzer.model.types.Type.<init>(Type.java:35)
	at com.sebastian_daschner.jaxrs_analyzer.model.types.Types.<clinit>(Types.java:69)
	... 41 more
Caused by: javassist.NotFoundException: javax.json.Json
	at javassist.ClassPool.get(ClassPool.java:452)
	at com.sebastian_daschner.jaxrs_analyzer.model.types.TypeExtractor.toErasuredClass(TypeExtractor.java:39)
	at com.sebastian_daschner.jaxrs_analyzer.model.types.Type.<init>(Type.java:32)
	... 42 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by sdaschner** [comment]
I see. Seems like the JSON-P API isn't loaded by the Javassist framework.

Could you please post the output of the JAX-RS Analyzer plugin part of the Maven debug mode (`-X` flag)? And have you tried using the version `0.7` - without SNAPSHOT?

**Comment by jeff9finger** [comment]
Will try without SNAPSHOT and post what you ask when I get a chance. Thanks for the quick response!

**Comment by jeff9finger** [comment]
Using version 0.7

mvn -X jaxrs analyzer section
[INFO] --- jaxrs-analyzer-maven-plugin:0.7:analyze-jaxrs (default) @ tract-api ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=71, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=32, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=1, ConflictResolver.conflictItemCount=70, DefaultDependencyCollector.collectTime=32, DefaultDependencyCollector.transformTime=1}
[DEBUG] com.sebastian-daschner:jaxrs-analyzer-maven-plugin:jar:0.7:
[DEBUG]    javax.json:javax.json-api:jar:1.0:runtime
[DEBUG]    org.javassist:javassist:jar:3.20.0-GA:runtime
[DEBUG]    com.sebastian-daschner:jaxrs-analyzer:jar:0.7:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-model:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:3.3.3:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.0:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0:compile
[DEBUG]    org.apache.maven:maven-core:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-settings:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.3.3:compile
[DEBUG]          org.apache.maven:maven-builder-support:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.3.3:compile
[DEBUG]          com.google.guava:guava:jar:18.0:compile
[DEBUG]       org.apache.maven:maven-aether-provider:jar:3.3.3:compile
[DEBUG]          org.eclipse.aether:aether-spi:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-impl:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-api:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-util:jar:1.0.2.v20150114:compile
[DEBUG]       org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.5:compile
[DEBUG]          javax.inject:javax.inject:jar:1:compile
[DEBUG]          aopalliance:aopalliance:jar:1.0:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:3.0.20:compile
[DEBUG]       org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG] Created new class realm plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7
[DEBUG] Importing foreign packages into class realm plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7
[DEBUG]   Included: com.sebastian-daschner:jaxrs-analyzer-maven-plugin:jar:0.7
[DEBUG]   Included: javax.json:javax.json-api:jar:1.0
[DEBUG]   Included: org.javassist:javassist:jar:3.20.0-GA
[DEBUG]   Included: com.sebastian-daschner:jaxrs-analyzer:jar:0.7
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.0
[DEBUG]   Included: javax.annotation:jsr250-api:jar:1.0
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0
[DEBUG]   Included: org.apache.maven:maven-builder-support:jar:3.3.3
[DEBUG]   Included: com.google.guava:guava:jar:18.0
[DEBUG]   Included: org.eclipse.aether:aether-util:jar:1.0.2.v20150114
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.5
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.21
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.20
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG] Configuring mojo com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7:analyze-jaxrs from plugin realm ClassRealm[plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.7:analyze-jaxrs' with basic configurator -->
[DEBUG]   (f) backend = swagger
[DEBUG]   (f) buildDirectory = /Users/jeff/Workspaces/Tract/trunk/tract-projects/tract/tract-api/target
[DEBUG]   (f) deployedDomain = example.com
[DEBUG]   (f) outputDirectory = /Users/jeff/Workspaces/Tract/trunk/tract-projects/tract/tract-api/target/classes
[DEBUG]   (f) project = MavenProject: com.transverse.bleep:tract-api:1.28.4-SNAPSHOT @ /Users/jeff/Workspaces/Tract/trunk/tract-projects/tract/tract-api/pom.xml
[DEBUG] -- end configuration --
[INFO] analyzing JAX-RS resources, using Swagger backend

**Comment by sdaschner** [comment]
Thanks for the quick response - have been on holiday the last days ;-)

Hehe, the interesting part is after the `[INFO] analyzing JAX-RS resources, using Swagger backend` line... The lines I'm interested in are from `[DEBUG] Dependency paths are: ...` till `[DEBUG] Analysis took x ms`.

But I guess the problem here is the JavaEE dependency which is used... Are you using the JavaEE 7 API?

**Comment by jeff9finger** [comment]
Not specifically JEE7

**Comment by sdaschner** [comment]
Ok, this is the problem here, the Analyzer currently tries to load classes from the JavaEE 7 API (JSON-P and other which might not be included if the dependency is e.g. JAX-RS solely).

Will try to separate them and make the process usable without the whole JEE API.

Thanks for testing!

**Comment by hmpatel** [comment]
+1 for removing the dependency on JEE  API

**Comment by sdaschner** [comment]
Hi guys,

Fixed in sdaschner/jaxrs-analyzer-maven-plugin@43a2ca3. Will be included in the next version.
In the meantime would you be so kind to test the `0.8-SNAPSHOT` version? :-)

**Comment by vania-pooh** [comment]
@sdaschner just tested with 0.8-SNAPSHOT (9c851ab51dc4758b9ed8f8d42a7a187c85ab7e1c), Jersey 2.21 and Maven 3.3.3. Works well. Thank you for the fix. Could you release the stuff?

**Comment by sdaschner** [comment]
Just released version `0.8`. Please update your dependencies :-)

**Comment by vania-pooh** [comment]
Thanks a lot.

**Comment by jeff9finger** [comment]
Awesome. Thank you!
-jeff
