### ISSUE TITLE
[minor] IntelliJ maven editor, reports invalid elements in plugin configuration 

### ISSUE THREAD

**Issue by javapapo** [sdaschner/jaxrs-analyzer#29]
* Maven 3.3.3
* Java 8
* IntelliJ 1.4.1 

It seems that when I add in my pom the plugin configuration, the editor reports 2 sub elements as invalid. Backend and deployedDomain.

```xml
   <configuration>
         <backend>plaintext</backend>
          <deployedDomain>something</deployedDomain>
    </configuration>
```
See attached [image](http://postimg.org/image/uougvhtbd/).

**Comment by sdaschner** [comment]
Yes, can confirm that.
Took me a while to identify the error :-)

Could you please test the latest `0.9-SNAPSHOT` version of the Maven Plugin?

You will have to add:

```
<pluginRepositories>
    <pluginRepository>
        <id>ossrh-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
```

If the warning still exists, try to restart & invalidate caches of IntelliJ.

Does that help?

**Comment by javapapo** [comment]
Yes, it seems that the validation works. I will be waiting for your 0.9 release on central :). Keep it up and thanks for your time.
