### ISSUE TITLE
All definitions are named definition_*

### ISSUE THREAD

**Issue by TheNitek** [sdaschner/jaxrs-analyzer#33]
I'm using jaxrs-analyzer as a command line tool to generate the swagger.json which seems to work good, but unfortunately all my definitions are called definition_1, defintion_2 ... instead of the class names. Is this there a way to change this?

**Comment by sdaschner** [comment]
Same story here :-)
Resolved in fb9a2c1 and will be added in `0.9` shortly.
Feel free to test the `0.9-SNAPSHOT` version - available in the Maven snapshot repository.
