### ISSUE TITLE
Enable sorting in all backend formats

### ISSUE THREAD

**Issue by TheNitek** [sdaschner/jaxrs-analyzer#34]
I'd like to use the jaxrs-analyzer output to create a diff on different API versions, which works quite well in most cases. Unfortunately in some cases the order of the status codes (and I think also the URLs) in the output differs (I guess due to refactorings in our code, which change their order of appereance).
It would be nice to be able to sort the output (URLs alphabetical, status codes by number) to make them comparable.

**Comment by sdaschner** [comment]
Resolved in fb9a2c1 and will be added in `0.9` shortly.
Feel free to test the `0.9-SNAPSHOT` version - available in the Maven snapshot repository.

**Comment by TheNitek** [comment]
I just realized that sorting is now only available for the swagger backend, but actually I think it would be far more usefull for the "text" output. Would be great if you could add this as well.

**Comment by sdaschner** [comment]
Resolved in bec320d.
The `0.9-SNAPSHOT` version has been updated.
