### ISSUE TITLE
Consider inheritance in type analysis

### ISSUE THREAD

**Issue by fcroci** [sdaschner/jaxrs-analyzer#38]
The fields of a super-class are not listed in the model representation both in Response and in Request parameters.

For ex. I have 
```@POST
  public Response createUser( Guest guest, @Context UriInfo uriInfo )
  {
      ...
     return Response.ok(nGuest).build();
  }
```

where `Guest` extends the class `User`.

In the json representation of the Response and  Parameter request only the specific attributes of `Guest` are listed but not the attributes defined in `User` (like firstName, lastName, ...).

![example](https://cloud.githubusercontent.com/assets/15671715/10970263/d30e636e-83cd-11e5-9939-7d158e19a8f5.jpg)

**Comment by sdaschner** [comment]
Solved by moving the internals to ASM.
