### ISSUE TITLE
Support multiple @Produces media types

### ISSUE THREAD

**Issue by kmoralesmartin** [sdaschner/jaxrs-analyzer#39]
This annotation shows up with only the first listed media type in the generated rest-resources.txt:

@Produces ({MediaType.TEXT_PLAIN, MediaType.APPLICATION_JSON, MediaType.APPLICATION,XML})

Generated plaintext:
Response:
  Content-Type: text/plain

**Comment by sdaschner** [comment]
Can you give me some more information when this error occurs? The Analyzer can indeed handle multiple media types. Just tested such a situation and it worked as expected in my case:

```
@GET
@Produces({MediaType.TEXT_PLAIN, MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
public List<Model> getModels() {
    return testStore.getModels();
}
```

produces:

```
...
 Response:
  Content-Type: application/json, application/xml, text/plain
  Status Codes: 200
...
```

Are you using the latest `0.9` version?

**Comment by sdaschner** [comment]
Any updates on this? I'm closing for now, feel free to re-open again.
