### ISSUE TITLE
Support tags for swagger

### ISSUE THREAD

**Issue by simdevmon** [sdaschner/jaxrs-analyzer#40]
It would be nice if the jaxrs-analyzer would support Swagger tags. I tried the Maven plugin v0.9 and all resources are listed under the default tag. 

In my opinion the API would be better readable, if the first path element after the basePath would be used as a tag.

For example like in the petstore: http://petstore.swagger.io/v2/swagger.json

Host + BasePath are: `http://petstore.swagger.io/v2/`
`http://petstore.swagger.io/v2/store/inventory` -> new tag "store"
`http://petstore.swagger.io/v2/pet/findByStatus` -> new tag "pet"

To provide backward compatibility this could be provided as an optional switch.

**Comment by sdaschner** [comment]
I see. Yes, this could actually increase the readability, though it may be a bit, "dangerous" or rather inflexible to rely on exactly the first path part for the tag. What if someone uses `/resources/v2` or similar...

But though I think it would be a nice feature to add an optional configuration option (`renderSwaggerTags` or something), which does exactly this.

I'll add that to my list, but as always feel free to fork & PR ;-)

Thanks for your contribution!

**Comment by simdevmon** [comment]
I will have a look! 

To get more flexibility we could add an additional configuration option like `swaggerTagsStartDepth` which defaults to 1 (= base path), but could be changed if there are path elements at the beginning like `<basePath>/v2/...`, which should not be used for tag generation.

**Comment by sdaschner** [comment]
Added in df9583ceed8dc8696cf55d7ffcbc53983b5d5712.
