### ISSUE TITLE
Incorrect Response Model Generation

### ISSUE THREAD

**Issue by TheNitek** [sdaschner/jaxrs-analyzer#44]
I have a few classes like this (incl. getters/setters):

```
public class ReleaseFamily implements Serializable {
    private String revision;
    private Product product;
    private Map<Integer, Release> releases = new HashMap<Integer, Release>();
}
```

```
public class Product implements Serializable {
    private String productName;
    private String company;
    private Long version;
}
```

When running jaxrs-analyzer now, I got the following Swagger model:

```
		"ReleaseFamily": {
			"properties": {
				"revision": {
					"type": "string"
				},
				"product": {
					"$ref": "#/definitions/NestedType_2"
				},
				"releases": {
					"$ref": "#/definitions/NestedType_2"
				}
			}
		},
		"Product": {
			"properties": {
				"productName": {
					"type": "string"
				},
				"company": {
					"type": "string"
				},
				"version": {
					"type": "number"
				}
			}
		},
		"NestedType_2": {
			"properties": {
				"somethingTotallyDifferent": {
					"type": "string"
				},
				"alsoSomethingElse": {
					"type": "string"
				},
				"somethingElse": {
					"type": "string"
				}
			}
		},
```

So both "Product" and "Map<Integer, Release>" are defined as "NestedType_2" which contains totally wrong attributes (from some entities not at all involved here).

**Comment by sdaschner** [comment]
This seems weird... Which version are you using?

Will test your example as soon as I have more time (the days before and during JavaLand are now too busy...)

Thanks for issuing!

**Comment by TheNitek** [comment]
Version 0.9 of the maven plugin.
Of course the example is stripped down quite a bit, so let me know if you need more input.

**Comment by RickDeckard76** [comment]
Hi!
First all, really good work!

My problem is that the generated documentation is not right in every cases.
For example, I have this rest method:

`	@GET
	@Path("/movements/qi/all")
	@Produces(MediaType.APPLICATION_JSON)
	public Response getAllQiMovements(			
			@QueryParam("fiscalYear") int fiscalYear,
			@QueryParam("userId") int userId,
			@QueryParam("counterPartyId") int counterPartyId) {
		
		List<QiMovementVO> movements = null;
		try {
			movements = movementService.getAllQiMovements(fiscalYear, userId, counterPartyId);
		} catch(Exception e) {
			throw new WebApplicationException(buildInternalServerErrorResponse(e, errorsMap));
		}
		return buildOKResponse(movements);
	}
`

The code above includes calls to two private methods, that are:

`	private Response buildOKResponse(Object returnedObject) {
		return Response.status(Status.OK).entity(returnedObject).build();		
	}
`

and the buildInternalServerErrorResponse that, in short, is defined as below:

`	protected Response buildInternalServerErrorResponse(Exception e, final Map<String, String> errorsMap) {
               [...] // Some code here to manage the error response
               SystemError systemError = [...]; // A JAXB SystemError is generated
		return Response.status(Status.INTERNAL_SERVER_ERROR).entity(systemError).build(); // Build the error response
	}
`

I use the jaxrs-analyzer's maven plugin configured to build an asciidoc. After running maven (e.g. clean install), the generated asciidoc is:

`GET data/movements/qi/all:
 Request:
  No body
  Query Param: counterPartyId, int
  Query Param: fiscalYear, int
  Query Param: userId, int

 Response:
  Content-Type: application/json
  Status Codes: 200
   Response Body: com.xxx.ws.model.SystemError (application/json): 
{"code":"string","title":"string","message":"string"}

  Status Codes: 500
   Response Body: java.lang.String
`

The 200's response body is not correct; as you can see in the source code above, the returned json is a list of entities of type QiMovementVO (in java: List<QiMovementVO>).
The strange think is that the indicated class com.xxx.ws.model.SystemError is a JAXB that is built in the private method "buildInternalServerErrorResponse" and should be created when an exception occurs.
Consider that for other REST method, that are very very similar to the one described above, all works fine.

Thx.

**Comment by sdaschner** [comment]
@TheNitek Sorry, for the late response. This has been fixed by moving the internals from Javassist to ASM. Feel free to try the `0.10-SNAPSHOT` version.

**Comment by sdaschner** [comment]
@RickDeckard76 This should as well be resolved in the latest version. Feel free to try the SNAPSHOT version (you have to add the Maven snapshot repositories).

Thank you both for issuing that!
