### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by gbourant** [sdaschner/jaxrs-analyzer#49]
It was working for a month but I get the following issue now.
Exception in thread "main" java.lang.StackOverflowError.

 at java.util.AbstractSet.hashCode(Unknown Source)
        at com.sebastian_daschner.jaxrs_analyzer.model.elements.Element.hashCode(Element.java:92)
        at java.util.Objects.hashCode(Unknown Source)
        at java.util.HashMap$Node.hashCode(Unknown Source)
        at java.util.AbstractMap.hashCode(Unknown Source)

The problem happens when you are returning JsonObject at your method , after i returned another type the error was gone.

**Comment by sdaschner** [comment]
Could you please provide the full stack trace and how your method which returns JsonObject looks like? Totally fine to make names etc. anonymous, but the structure should be the same.

I suspect some issue because of recursion etc...

**Comment by gbourant** [comment]
This is how the method looks like.
```
@POST
public JsonObject Pricing(PricingRequest pr) {

  JsonObjectBuilder Pricing1 = ExternalService1.Pricing(pr);
  JsonObjectBuilder Pricing2 = ExternalService2.Pricing(pr);

   return Json.createObjectBuilder()
                .add("ExternalCompany1", Pricing1.build())
                .add("ExternalCompany2", Pricing2.build())
                .build();
}
```
In my method i call external services and based on external's response i build the JsonObject.
Based on the PricingRequest both of the ExternalServices return different results.
