### ISSUE TITLE
Consider enum parameters as String values in backends

### ISSUE THREAD

**Issue by sasacoh** [sdaschner/jaxrs-analyzer#50]
Seems like java enum type parameters are not converted into valid swagger.json format:

`@QueryParam("level") EnumLogLevel `

where EnumLogLevel is:
```
public enum EnumLogLevel {
		FATAL,
		ERROR,
		WARN,
		INFO,
		DEBUG,
		TRACE,
		ALL
	}
```

results in:

```
{
            "name": "level",
            "in": "query",
            "required": true,
            "type": "object"
}
```

Tested with swagger editor (http://editor.swagger.io/#/) -> error output:

```
...
type:  "Swagger Error"
description:  "Not a valid parameter definition"
```

Swagger json generated by maven plugin: <version>0.9</version>

**Comment by darylteo** [comment]
I can try and look at this together with the new issue I started regarding parameter classes, on the weekend probably.
