### ISSUE TITLE
[0.9] Classpath does not extract Class-Path attribute in jar Manifest.

### ISSUE THREAD

**Issue by darylteo** [sdaschner/jaxrs-analyzer#53]
When developing on Windows, users may run into command length limitations due to large classpaths.

We can get around this by creating a "pathing jar" to declare classpaths to the JVM using a manifest.

jaxrs-analyzer does not use the jvm classpath, instead opting to have classpath passed in via a separate -cp parameter. They get added into the javassist classpool without any regard for Class-Path 

```java
    /**
     * Adds the location to the class pool.
     *
     * @param location The location of a jar file or a directory
     */
    private void addToClassPool(final Path location) {
        if (!location.toFile().exists())
            throw new IllegalArgumentException("The location '" + location + "' does not exist!");
        try {
            ClassPool.getDefault().insertClassPath(location.toString());
        } catch (NotFoundException e) {
            throw new IllegalArgumentException("The location '" + location + "' could not be loaded!", e);
        }

    }
````

An example of loading Class-Path can be found in the links below. 1 uses URLClassLoader's default behaviour of addURL (doesn't seem documented, but should adhere to the manifest) or use introspection.

Will submit a PR soonish.

[Reference](https://docs.oracle.com/javase/tutorial/deployment/jar/downman.html)
[Solution 1](http://stackoverflow.com/questions/37260774/load-library-jars-with-javassist)
[Solution 2](http://stackoverflow.com/questions/10953373/loading-another-class-with-javassist)

**Comment by sdaschner** [comment]
Yes you're right. The fact that the classes are currently added to Javassist's classpath is btw causing several problems.

This is why I'm currently switching from Javassist to ASM. Please also see the ASM branch.

Thanks for your efforts! The newer version with ASM won't have these troubles.

**Comment by sdaschner** [comment]
Will close the issue for now; feel free to reopen with the ASM version if classpath error still exist then.

**Comment by darylteo** [comment]
No problems. Thanks for letting me know.
