### ISSUE TITLE
Respect @DefaultValue annotation for parameters and Swagger output

### ISSUE THREAD

**Issue by darylteo** [sdaschner/jaxrs-analyzer#55]
```java
@DefaultValue("") @QueryParam("priceSensitive") String priceSensitive
````

should yield 

```json
          {
            "name": "priceSensitive",
            "in": "query",
            "required": false,
            "type": "string"
          }
````

---

```java 
@QueryParam("priceSensitive") String priceSensitive
````

should yield 

```json
          {
            "name": "priceSensitive",
            "in": "query",
            "required": true,
            "type": "string"
          }
````

**Comment by darylteo** [comment]
@sdaschner thanks for accepting the proposal (I'm assuming?)

Not really sure where to start looking at this. I'm looking at SwaggerBackend.java, and I'm seeing MethodParameters.java and I'm seeing Map<String,String> of name -> type for queryParams. 

I believe in order to implement this, a data structure is needed (possible MethodParameter), which contains name, type, and required.

Right path?

**Comment by sdaschner** [comment]
Yes exactly, you would need another data structure than the current `Map<String, String>`, e.g. something like your suggested MethodParameter. But as you saw that changes a lot of things. But nevermind, keep going and let me know if you need help with some specific problems!

**Comment by darylteo** [comment]
Yay my build is fixed now with a newer JDK version (how have I survived for so long on u25?)

Decided on a more low-key - add a defaultValues map alongside all the other maps (due to the visitor pattern being used). Then check for default value params when generated the spec. This is better as MethodParameters becomes more of a description of the parameters instead of a domain specific concept of required parameters.

**Comment by darylteo** [comment]
@sdaschner should be closed?

**Comment by sdaschner** [comment]
Yep
