### ISSUE TITLE
[master] IndexOutOfBoundsException with generic superclass

### ISSUE THREAD

**Issue by darylteo** [sdaschner/jaxrs-analyzer#58]
```java
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.sebastian_daschner.jaxrs_analyzer.model.JavaUtils.getTypeVariables(JavaUtils.java:340)
        at com.sebastian_daschner.jaxrs_analyzer.model.JavaUtils.resolvePotentialTypeVariables(JavaUtils.java:433)
        at com.sebastian_daschner.jaxrs_analyzer.model.JavaUtils.getReturnType(JavaUtils.java:326)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.results.JavaTypeAnalyzer.mapGetter(JavaTypeAnalyzer.java:196)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.results.JavaTypeAnalyzer.lambda$analyzeClass$3(JavaTypeAnalyzer.java
````

Took me awhile to figure out what was happening. The type analyzer does not handle concrete subclasses of generic types. Not sure if this is fixable in its current state due to erasure but I'll give it another crack tomorrow.

Code fails to identify the generic return type of getData().

---

```java

// lombok generating getters and setters
@Data
public abstract class Json<T> {
    private T data;
}

@Path("/resource")
@Produces("application/json")
public class SomeResource {
    @GET
    public Many findAll() {
       ...
    }

    public static class Many extends Json<List<ResourceEntity>> {
    }
````

---

Use case: 

 - standardised return types for all endpoints (success, errors, JSONAPI spec stuff etc.)
 - concrete models for swagger spec (above generates nice class names like SomeResourceMany). Returning Json<List<ResourceEntity>> leads to weird behaviour as well (separate issue for another time)

**Comment by darylteo** [comment]
Battled this for a day, can't see an out. Sad that this has broken my previous build. Damn generics.

**Comment by darylteo** [comment]
@sdaschner just did another similar repro for this issue.

**Comment by sdaschner** [comment]
Looked further into it and of course you were right. Changed that line but we should in general add more use cases for system tests...

Thanks!

**Comment by darylteo** [comment]
Haven't really had the time to look into the system tests, sorry. Not really sure how it fits in with this repository (do I need to mvn install it and have mvn pick it up as a plugin or something?). 

Being able to run the tests in intellij while I'm developing is easier for me currently obviously.

> **of course** you were right

Thanks! I'm flattered ;)

**Comment by sdaschner** [comment]
The reason for the system test is that we don't want to loose any test scenarios in which we invested time. Running in the IDE is more productive, yes, but how about having some (temporary) tests in the IDE and then moving it to the system test project after fixing it -- as regression tests?

The system test project takes the Analyzer from either Maven central (snapshot) or your local version in your Maven repository. So if you build a new JAX-RS Analyzer version via `mvn clean install` that will be taken when you run the system test project with `./run-test.js`.
