### ISSUE TITLE
Support String auto-convertable types (see JSR 339 3.2)

### ISSUE THREAD

**Issue by darylteo** [sdaschner/jaxrs-analyzer#59]
Hey @sdaschner,

   not even sure whether this is possible, but this is a very valuable concept that this library could support. 

https://codahale.com/what-makes-jersey-interesting-parameter-classes/

At the moment when I try it with [Dropwizard params](https://github.com/dropwizard/dropwizard/tree/master/dropwizard-jersey/src/main/java/io/dropwizard/jersey/params) the type analyzer just sees "Object" by default.

We can perhaps follow these rules from Jersey:

> The type of the annotated parameter, field or property must either:
> 
> …
> Be a primitive type. (already supported)
> Have a constructor that accepts a single String argument. (**not supported**)
> Have a static method named valueOf that accepts a single String argument (see, for example,  Integer#valueOf(String)). (**not supported**)

Use cases: using these parameter classes will allow inappropriate parameters to be met with a 400 - bad request instead of the default 404 - not found as the parsing will throw exceptions. The alternative would be to have everything as String, then do the parsing in the resource method (not DRY). The spec will also simply have all Strings.

**Comment by sdaschner** [comment]
Good point!

Actually this is nothing Jersey specific; it's defined in JSR 339 (see 3.2 Fields and Bean Properties).

**Comment by darylteo** [comment]
So not sure what I was smoking at the time, but right now I can't see how we can even get the appropriate javascript type mapping from a auto-convertable type. All we know is that it converts a String into something.

Unless you were intending that the swagger output denotes a "string" parameter instead of "object".

**Comment by darylteo** [comment]
@sdaschner not sure what you would like at the moment: put the concrete class in MethodParameter.type, then map to String in SwaggerUtils.toSwaggerType (and leave accordingly in PlainText and AsciiDoc), or put String in MethodParameter.type, and have everything else as is.

**Comment by sdaschner** [comment]
Good question.

I tend more to including the actual type -- and then convert them in the backends accordingly. This may help in some situations where we wanna know the actual type (to maybe provide more information how it is serialized to String later).
