### ISSUE TITLE
Security Definitions

### ISSUE THREAD

**Issue by darylteo** [sdaschner/jaxrs-analyzer#60]
Hmm, this is a tough one. I don't actually think this is possible but I'll check at least. 

I'd like to somehow generate SecurityDefinition entries in the swagger spec. 

Looking at how authentication is handled, there're all these filters that we don't have access to. We can get `@Context` annotation in Resource, but no way to describe what form of security is required.

Thoughts? I'll probably simply introduce an additional build step before swagger-codegen to inject the required json at this stage.

**Comment by sdaschner** [comment]
Puh, this would be hard to get...

It would be possible to read a potentially existent web.xml (or other deployment descriptors), but as a) many app servers offer non-standard security features and more important b) a lot of enterprise setups use a proxy server or authentication portal upfront (without any change to see that in the EE source) I would leave it out for now.
Too much required work for a small chance to get it right (in a generally usable way).

**Comment by sdaschner** [comment]
Anyway, there might be a possibility to manually add that information to the generated doc (by adding extra configuration in the pom or via CLI). Depending on the options Swagger offers of course, but I haven't looked at Swagger's SecurityDefinitions yet TBH.

So feel free to investigate in that direction -- but I wouldn't bloat the configuration too much, only if there is a really easy way...

**Comment by darylteo** [comment]
The swagger spec regarding security definitions is quite significant. Highly doubt it will be something configurable. Each resource path can be arbitrarily defined as required 1-many security levels and scopes. 

If I figure something out I'll drop another line here. Could be useful for other users in the future.

**Comment by darylteo** [comment]
If anyone else comes around in the future, here's how I'm solving it (at a basic level) using Gradle:

```groovy
// in your jaxrsanalyzerdoc task

doLast {
        def json = new groovy.json.JsonSlurper().parse(file(outputFile))
        json.securityDefinitions = [
            "auth": [
                "type": "basic",
            ],
            "jwt" : [
                "type": "apiKey",
                "name": "Authorization",
                "in"  : "header",
            ],
        ]

        json.security = [
            [ "auth": [] ]
        ]

        file(outputFile).write(groovy.json.JsonOutput.toJson(json));
    }
````

**Comment by darylteo** [comment]
@sdaschner so I had a dream (literally, I dream about this shit in my sleep somehow), and thought of a configuration option which you can point to another json/yml spec which you can tell jaxrsanalyzer to deep-merge in. Removal can simply be "null" entries.

This really should be a general purpose utility people make  (I'll probably do it for my build separately for example), but thought I'd suggest it as an option if you want to consider it.

**Comment by sdaschner** [comment]
> literally, I dream about this shit in my sleep somehow

I know that feeling :-)

Yes, I see what you mean, however this is a really complex change and targets more to post-processing output files (like you would on AsciiDoc for instance). So probably a better target for a subsequent plugin call like a modify-something-plugin which modifies your output files, i.e. the swagger output by merging another json/yml snippet in.

So would be a cool extra but probably too much and not the right scope for the Analyzer.
