### ISSUE TITLE
Analyze reference to header param class field before including in doc

### ISSUE THREAD

**Issue by oluwasayo** [sdaschner/jaxrs-analyzer#70]
```
@Path("bank-account")
public class BankAccountEndpoint extends AbstractEndpoint {

  @HeaderParam("sessionId")
  private String sessionId;

  @EJB
  private BankAccountHandler handler;

  @GET
  public BankAccount getAccount(String accountId) {
    return handler.getAccount(accountId);
  }

  @POST
  public BankAccount createAccount(String bankCode, String accountName, String accountNumber) {
    BankAccount ba = new BankAccount(bankCode, accountName, accountNumber);
    return handler.createBankAccount(getUser(sessionId), ba);
  }
}
```

The analyzer should generate:
```GET rpc/bank-account:```

```POST rpc/bank-account: 
Header Param: sessionId, java.lang.String```

No `Header Param: sessionId, java.lang.String` should be generated for the `GET` request since it doesn't reference the class-level header param.

**Comment by sdaschner** [comment]
Having a param at class level makes that available for all of the resource methods no matter whether it's referenced or not -- of course you could argue that you couldn't use it, but still the JAX-RS implementation tries to inject that param (from the HTTP header in your case).

If you don't need that `sessionId` in the `POST` method only then you can just inject it there as method parameter.

Also your example for `createAccount` doesn't follow the JAX-RS standard (see JSR 339, chapter 3.3.2.1) as it has several entity parameters.

**Comment by oluwasayo** [comment]
RE: Also your example for createAccount doesn't follow the JAX-RS standard

That's a contrived example, they  could easily be query params. I'll update the example.
