### ISSUE TITLE
StringIndexOutOfBoundsException for ApplicationPath = "/"

### ISSUE THREAD

**Issue by MarkusS75** [sdaschner/jaxrs-analyzer#78]
If the basepath of the application is set to "/" PathNormalizer.normalize() causes a StringIndexOutOfBoundsException.

```
@ApplicationPath("/")
public class JAXRSConfiguration extends Application {

```

**Comment by sdaschner** [comment]
Yes, that should already be fixed in the `0.11-SNAPSHOT` version. Could you please confirm with that version and re-open if not?
