### ISSUE TITLE
Unable to analyze static inner class of interface

### ISSUE THREAD

**Issue by oluwasayo** [sdaschner/jaxrs-analyzer#84]
`error: cannot find symbol
@Priority(Interceptor.Priority.APPLICATION)
                                   ^`

Import statements:
`import javax.annotation.Priority`
`import javax.interceptor.Interceptor`

**Comment by sdaschner** [comment]
I'm pretty sure that's an error coming from the JavaDoc tool analysis and related to #83. Will let you know as soon as the fixed version is available, that should be resolved automatically.

**Comment by sdaschner** [comment]
Please retry with `0.12`. Also see https://blog.sebastian-daschner.com/entries/javadoc_jaxrs_analysis

**Comment by sdaschner** [comment]
Did that fix the error? Feel free to reopen if not.
