### ISSUE TITLE
There is a way to hide resource properties? 

### ISSUE THREAD

**Issue by rmpestano** [sdaschner/jaxrs-analyzer#87]
In **[swagger-doclet](https://github.com/conorroche/swagger-doclet#supported-javadoc-tags-and-annotations)** we used **@exclude** javadoc annotation at resource/method or field level to remove a resource from generated swagger json.

There is a way to achieve that with this plugin?

**Comment by sdaschner** [comment]
Not really. There was a similar request in #36. We could include an analysis configuration (like `<excludes>` in the Maven plugin config) to control that. So far the scope of the tool was to stay as close to the actual JAX-RS output as possible.

Do you see a big advantage in make that controllable? If yes then we should incorporate that feature.

**Comment by rmpestano** [comment]
So If you create dedicated pojos for each endpoint you will NOT benefit from this but If you reuse your JPA entities and mark undesired properties with @JsonIgnore for example, it would be nice to exclude them from swagger too.

**Comment by rmpestano** [comment]
I've got it working here but it needs some changes.

First I've added dependency to [jackson-annotations](http://search.maven.org/#artifactdetails%7Ccom.fasterxml.jackson.core%7Cjackson-annotations%7C2.8.5%7Cbundle)  which doesn't bring any transitive dependencies.

Then I've reworked JavaTypeAnalyzer to look for @JsonIgnore in _analyze_ method. Here is the diff: http://www.diff-online.com/view/586277a8ed8ee

The only thing I could not make was to read the annotation @JsonIgnoreProperties value here:

```
private static boolean shouldIgnore(Field field) {
        if (isAnnotationPresent(field,JsonIgnore.class) || isAnnotationPresent(field.getDeclaringClass(), JsonIgnoreType.class)) {
            return true;
        }

 JsonIgnoreProperties annotation
       if(isAnnotationPresent(field.getDeclaringClass(),JsonIgnoreProperties.class)) {
            JsonIgnoreProperties jsonIgnoreProperties = 
getAnnotation(field.getDeclaringClass(), JsonIgnoreProperties.class); //class cast exception Proxy cannot be cast to JsonIgnoreProperties
            for (String ignoreField : jsonIgnoreProperties.value()) {
                if (field.getName().equals(ignoreField)) {
                    return true;
                }
            }
        } 
        return false;
```

Any idea on how to read the annotation values?

**Comment by sdaschner** [comment]
Ah ok, so I got it. Have you tried excluding the unwanted property with `@XmlTransient`? That is a workaround for some JSON mapping frameworks like Jackson for not having JSON related annotations in the standard (yet). The Analyzer should ignore these properties then.

**Comment by sdaschner** [comment]
I like your approach, though the initial idea of the tool was to stay as close to the standards as possible -- and as soon as that works completely to go on from that with the most commonly used frameworks. What do you think?

**Comment by rmpestano** [comment]
The main problem is that APIs using @JsonIgnore will have responses in swagger-ui that differs from what the API documentation is saying.  

What other frameworks se should handle?

**Comment by rmpestano** [comment]
> Have you tried excluding the unwanted property with @XmlTransient?

So @XmlTransient excludes de field from swagger definition BUT when I invoke the endpoint in swagger-ui the field is present cause my JaxRS implementation (resteasy) doesn't take @XmlTransient into account.

**Comment by rmpestano** [comment]
About @XmlTransient RestEasy will not support it in favor of Jackson, as stated here: https://issues.jboss.org/browse/WFLY-801
