### ISSUE TITLE
Resources with same path but different @Consumes are ignored  

### ISSUE THREAD

**Issue by rmpestano** [sdaschner/jaxrs-analyzer#88]
JaxRS supports resources with same paths but with different **@Consumes** (content negotiation):

```
  @GET
  @Path("sample")
  @Consumes(MediaType.APPLICATION_JSON)
  public Response sample() {
    return Response.ok().build();
  }

  @GET
  @Path("sample")
  @Consumes("application/vnd.procergs-apm-v2+json")
  public Response sampleV2() {
    return Response.ok().build();
  }
```

Only the first resource is present in swagger.json:

```
/turmas/sample":{
            "get":{
                "consumes":[
                    "application/json"
                ],
                "produces":[
                    "application/json"
                ],
                "parameters":[
                ],
                "responses":{
                    "200":{
                        "description":"OK",
                        "headers":{
                        }
                    }
                },
                "tags":[
                    "turmas"
                ]
            }
        },
```

**Comment by rmpestano** [comment]
Note that same path with different **Produces** is working.

**Comment by sdaschner** [comment]
(Without having it tested right now:) Does it make a difference whether the method is `POST` / `PUT` and has a request body param? Just from an API perspective it wouldn't make sense to send a `Content-Type` (as controlled by `@Consumes`) for a `GET` request, right?

**Comment by rmpestano** [comment]
> Just from an API perspective it wouldn't make sense to send a Content-Type (as controlled by @Consumes) for a GET request

well for versioning (in some cases) it does so instead of  creating a "/v2/resource" we use content negotiation for having multiple versions of same resource. Here's an example using @Produces but can be done we @Consumes as well: http://stackoverflow.com/questions/4924034/easy-rest-resource-versioning-in-jax-rs-based-implementations

**Comment by sdaschner** [comment]
Yes, and I would say from just the API perspective it only makes sense with an `Accept` header from the client, as the resource should then be returned in the specific format. But if there is no request body (as in `GET`) the server doesn't have something to distinguish on? Or in other words, why not use the `Produces` and control with the `Accept` header on the client side?

**Comment by rmpestano** [comment]
"Or in other words, why not use the Produces and control with the Accept header on the client side?"
Yes, you're completely right it makes more sensei to rely on Accept header (but content-type also works with jaxrs hehe).  I will rely on @Produces, thanks
