### ISSUE TITLE
syntax error with tags in swagger.json

### ISSUE THREAD

**Issue by vboerchers** [sdaschner/jaxrs-analyzer#94]
If `renderSwaggerTags` the top-level `tags` element is rendered wrongly in `swagger.json`: jaxrs-analyzer generates an array of __tag names__ instead of __objects_ leading to validation warnings in http://editor.swagger.io/#/ .

It should be

    "tags": [
      {"name": "tag1"},
      {"name": "tag2"}
    ]

instead of

    "tags": [
      "tag1",
      "tag2"
    ]

### Details
According to the [json schema of swagger.json](http://23.22.16.221/v2/schema.json) the top level `tags` is a list of objects with the following syntax:

    "tags": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/tag"
      },
      "uniqueItems": true
    }
 
and #/definitions/tag resolves to

    "tag": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "externalDocs": {
          "$ref": "#/definitions/externalDocs"
        }
      },
      "patternProperties": {
        "^x-": {
          "$ref": "#/definitions/vendorExtension"
        }
      }
    },

**Comment by peter-janssen** [comment]
I'm still experiencing this issue with v0.12

**Comment by vboerchers** [comment]
That doesn't surprise me since there was no release since my fix (as far as I remember)

@sdaschner What is your plan on a 0.13 release? It would be great if #90 was included.

**Comment by sdaschner** [comment]
Yes, actually I'm planning to release the next version soon. Stay tuned ;-)
